name: Automation Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-automation-test:
    runs-on: windows-latest
    permissions: 
      contents: write

    steps:
    # Download repo
    - uses: actions/checkout@v4
    
    # Setup Java
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    # Setup Chrome / Browser
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1.7.2

    # Setup gradlew
    - name: Setup gradlew
      run: chmod +x gradlew

    # Execute gradle command for running cucumber test
    - name: Execute Test
      run: ./gradlew cucumber

    # Archive test result
    - name: Archive test result
      uses: actions/upload-artifact@v4.4.3
      if: always()
      with:
        name: Cucumber Report
        path: reports

    # Deploy to GitHub page
    - name: Deploy report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4.0.0
      with: 
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: reports
